version: "3"
services:
  bpm-db:
    image: postgres:latest
    ports:
      - 5432
    network_mode: bridge
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-bpm
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE 
         
  bpm-web:
    image: bpm-web:v26
    network_mode: bridge
    container_name: bpm-web
    expose:
      - 8092
    ports:
      - 8092:8092
    depends_on:
      - bpm-db
    links:
      - bpm-db
 
#docker system prune //limpa o cache
#sudo SPRING_PROFILES_ACTIVE=hml TESTE=teste docker-compose up --build
#sudo docker ps -a (imagens já criadas)
#sudo docker build -t api-gateway-web  .
#sudo docker run -p 8080:8080 -d <nome da imagem>
#sudo docker stop <nome da imagem>
#sudo docker rm <nome da imagem>
#sudo docker ps (imagens ativas)