version: "3"
services:
  bpm-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-bpm
    networks:
      - sca-bpm-network
  bpm-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bpm-web
    image: sca-bpm
    ports:
      - '8092:8092'
    depends_on:
      - bpm-db
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
    networks:
      - sca-bpm-network
networks:
    sca-bpm-network:
        driver: bridge 