version: "3"
services:

  bpm-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bpm-web
    image: sca-bpm
    ports:
      - '8092:8092'
    depends_on:
      - bpm-db
    environment:
    - PORT=8092
    - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  
  bpm-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-bpm
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
         
#docker system prune //limpa o cache
#SPRING_PROFILES_ACTIVE=test docker-compose up --build
#docker ps -a (imagens já criadas)
#docker build -t api-gateway-web  .
#docker run -p 8080:8080 -d <nome da imagem>
#docker stop <nome da imagem>
#docker rm <nome da imagem>
#docker ps (imagens ativas)