version: "3"
services:

   bpm-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bpm-web
    image: sca-bpm
    ports:
      - '8092:8092'
    depends_on:
      - bpm-db
    environment:
    - PORT=8092
    - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  
   bpm-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-bpm
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
 
#docker system prune //limpa o cache
#sudo SPRING_PROFILES_ACTIVE=hml TESTE=teste docker-compose up --build
#sudo docker ps -a (imagens já criadas)
#sudo docker build -t api-gateway-web  .
#sudo docker run -p 8080:8080 -d <nome da imagem>
#sudo docker stop <nome da imagem>
#sudo docker rm <nome da imagem>
#sudo docker ps (imagens ativas)